### ISSUE TITLE
Feature Request: Non-Staff Magical Items

### ISSUE THREAD

**Issue by Codex966** [jessev14/pf2e-staves#18]
Would love to see some more functionality in this module, allowing for modifications on the typical Staff-Spell implementation.

Items that could have a custom formula and independent well of charges, cast spells for non-spellcasters, choose how they recharge on rests or things like that. 
I just keep thinking about items like say, a Necklace of Fireballs or Artificer Spectacles that grant spells with their own independent charges. 
Could use a custom "Trait" tag from the Homebrew options on the item to flag it for the module to scrape and implement.  

Piggybacking off that (but perhaps a bit overreaching for this module) a way to grab Activated Effects from items (things like Belt of Regeneration or the Titan's Grasp) and add them to the Actions tab would make it even more flexible.

**Comment by jessev14** [comment]
This module was developed through a commission. I'm happy to merge a pull request if you'd like to make one. Otherwise feel free to reach out to me on Discord `enso#0361` if you'd like to discuss funding these features.
