### ISSUE TITLE
Compatibility with PF2e Spell Summary

### ISSUE THREAD

**Issue by MrChessur** [jessev14/pf2e-staves#2]
It would be nice if this had some compatibility with PF2e Spell Summary (https://github.com/reonZ/pf2e-spells-summary) As it helps cut down on the space the spell lists take up. Currently the spells will not cast while they are in the collapsed version of the Spell List.

![image](https://user-images.githubusercontent.com/28309284/209892252-9fd26bc5-fe33-40d2-9f04-2ee6c85ef5aa.png)

**Comment by jessev14** [comment]
This should be doable, but this module was funded by a commission. I unfortunately don't have the means to implement and maintain compatibility with other modules in my free time.

I'm happy to accept a pull request if you'd like to implement it yourself. Or you can reach out to me on Discord to discuss funding the development `enso#0361`.
