### ISSUE TITLE
Staff spell entry adding fails if there is a ritual entry

### ISSUE THREAD

**Issue by shun17** [jessev14/pf2e-staves#20]
For version 1.2.2

When adding a staff to a player which has a spellcasting entry for rituals the script throws
`main.js:256 Uncaught (in promise) TypeError: undefined. Cannot read properties of undefined (reading 'tradition')
[Detected 1 package: pf2e-staves]
    at main.js:256:93
    at ActorSpellcasting.map (commons.js:3332:26)
    at createStaveSpellcastingEntry (main.js:256:73)`

The problem is on line 256, when searching for `se.system.tradition.value`
`const mostCommonTradition = mostCommonInList(actor.spellcasting.map(se => se.system.tradition.value));`
An actor with a ritual entry has in his spellcasting list an entry like `{"rituals" => RitualSpellcasting}` that does not have the property `system`.

To solve the problem you can either filter out all ritual entries (I saw that all the ritual entries for my actors have the key `rituals`) or do some kind of null checking.

**Comment by shun17** [comment]
A simple solution is subtitute
`actor.spellcasting.map(se => se.system.tradition.value)`
with
`actor.spellcasting.map(se => se?.system?.tradition.value).filter(se => !!se)`

**Comment by shun17** [comment]
Link to pull request: https://github.com/jessev14/pf2e-staves/pull/21

**Comment by jessev14** [comment]
Re-open this if version 1.2.2 doesn't fix the issue.

**Comment by shun17** [comment]
Ther bug is on version 1.2.2

![image](https://user-images.githubusercontent.com/45995227/225644794-3e53f9a1-d811-4bf4-b156-1ecdc3391e85.png)

The version of pf2e is 4.9.3

![image](https://user-images.githubusercontent.com/45995227/225645019-b9a412f2-900f-4a2f-aafb-9059cd951fa7.png)

**Comment by jessev14** [comment]
Okay, see if 1.2.3 fixes it.

**Comment by shun17** [comment]
No, there are more problems in other use of `actor.spellcasting`. I will do a more thorough search and submit a new pull request with the complete fix

**Comment by shun17** [comment]
https://github.com/jessev14/pf2e-staves/pull/22 this could be all

**Comment by shun17** [comment]
Fixed, I'm closing the issue
