### ISSUE TITLE
Feature Request: NPC Compatibility

### ISSUE THREAD

**Issue by blacktrench** [jessev14/pf2e-staves#3]
Hey, is it possible to have the charge mechanic function with NPCS?

Right now when imported to an npc the staff list populates which is great and a time saver (much appreciated!)

But I cannot cast with the cast button as it has no charges (I can cast if I just click the icon but if possible I'd love to be able to manually add the charges if not automatic)

![image](https://user-images.githubusercontent.com/24504912/209898158-33dea2ad-781e-4b91-9cc3-8101580c55c8.png)

Hopefully this is doable, if not appreciate it either way :)

**Comment by jessev14** [comment]
Added in 1.0.4.
