### ISSUE TITLE
Broken on Remaster? [PF2e System v5.9.0]

### ISSUE THREAD

**Issue by 117ksk** [jessev14/pf2e-staves#38]
Looks like staves are no longer automatically creating spellcasting entries for new staves added to inventory after remaster update. Also looks like manual entries cannot be made using the "staff" type anymore (might be misremembering this being a feature before).

**Comment by fishrobe** [comment]
confirmed. Swithed a staff and the old spells disappeared but weren't replaced.

**Comment by roguedevjake** [comment]
```
caught (in promise) TypeError: undefined. actor.spellcasting.forEach is not a function
[Detected 1 package: pf2e-staves]
    at getHighestSpellslot (main.js:301:24)
    at createStaveSpellcastingEntry (main.js:285:30)
getHighestSpellslot @ main.js:301
createStaveSpellcastingEntry @ main.js:285
```
