### ISSUE TITLE
Feature Request: Toggle Visibility of Spell Levels Without Slots

### ISSUE THREAD

**Issue by velara** [jessev14/pf2e-staves#4]
Some of the other other types of spellcasting entries, such as spontaneous or prepared casting, include a button to hide spell levels without any slots which would be really nice for lower level staves so empty extraneous levels aren't taking up space. 

I've done some preliminary fiddling around in hopes of making this a PR rather than a request and the best I could manage was to get the button itself to show up without actually adding the functionality, but manipulating HTML with Javascript is not my forte.

The logic gate the produces the button normally is:  
{{#if (or entry.isPrepared entry.isSpontaneous entry.isInnate)}}
                                <a class="skill-name slotless-level-toggle" title="{{localize "PF2E.ToggleSlotlessSpellLevelsTitle"}}">
                                    <i class="{{#if entry.system.showSlotlessLevels.value}}fas{{else}}far{{/if}} fa-list-alt"></i>
                                </a>
                            {{/if}}
Which lives in the item-controls div.

**Comment by jessev14** [comment]
Added in version 1.1.0.
