### ISSUE TITLE
Always uses lowest level prepared spell when refreshing charges

### ISSUE THREAD

**Issue by MrChessur** [jessev14/pf2e-staves#5]
The feature that allows you to choose a spell slot to add charges has an issue where it will use the lowest level of the spell prepared rather than the one you choose if it is the same spell prepared at a higher level.

![GIF 1-3-2023 5-31-55 PM](https://user-images.githubusercontent.com/28309284/210452400-1568f2e6-d5ce-44b3-97e3-5e0cb04a8147.gif)

**Comment by jessev14** [comment]
Thanks for the report. Fixed in 1.1.1.
