### ISSUE TITLE
Cannot cast spells through staff, claims "Not enough slots"/Staff has too many charges

### ISSUE THREAD

**Issue by trapbuilder2** [jessev14/pf2e-staves#7]
Trying to cast a spell granted by a staff just gives a yellow "Cannot cast [spell] at [level], not enough spell slots". This happens regardless of how many charges are left on the staff

**Comment by jessev14** [comment]
Any character sheet modules? What version of the PF2e Staves do you have installed?

**Comment by trapbuilder2** [comment]
To my knowledge, the only other module I have that affects the character sheet is PF2e Workbench, though I had that previously and the Staves worked fine. I have version 1.1.2 of PF2e Staves, which Foundry tells me is the latest. I believe it stopped working upon upgrading to this version, or it broke when the pf2e system itself updated

**Comment by jessev14** [comment]
Gotcha, I'll take a look. Do you have libWrapper installed and enabled? That was a new requirement in the latest version of the module.

**Comment by trapbuilder2** [comment]
I had it installed, but apparently didn't have it enabled. Enabling it fixed the problem.

While I'm here, I have a different issue as well. The number of charges you get is supposed to be equal to the level of your highest spell slot, but my level 3 wizard (with druid archetype) is getting 9 charges.

**Comment by jessev14** [comment]
Can I get a screenshot of the spells tab of the character sheet?

**Comment by trapbuilder2** [comment]
Lots of spell fields so it's spread across 2 screenshots

![image](https://user-images.githubusercontent.com/15017349/213328494-2f893101-c3c8-40c8-9838-d8ef23c0f307.png)
![image](https://user-images.githubusercontent.com/15017349/213328542-f87fb347-02be-4b94-ae90-fcb101292faa.png)

**Comment by jessev14** [comment]
Hm, I'm not able to reproduce on my end. Would you be able to export the actor JSON file and attach it here? 
![image](https://user-images.githubusercontent.com/68755874/213366812-df29b636-74c4-4336-95ca-c7b57c3316ff.png)

**Comment by trapbuilder2** [comment]
GitHub doesn't support sending json files, is there somewhere else I can send it to?

**Comment by jessev14** [comment]
you can email it to me: jessevo321@hotmail.com

**Comment by trapbuilder2** [comment]
Sent

**Comment by jessev14** [comment]
Staves get a number of charges based on the character's highest available spell slot level. For some reason, the "School Spells" spellcasting entry on this character has slots up to level 9, which is why staves get 9 charges. My guess is at some point a 9th level spell was on this entry and then removed, but the slots weren't fixed.

I would try deleting and recreating this spell slot entry.

**Comment by trapbuilder2** [comment]
That fixed the issue, thanks for your help
