### ISSUE TITLE
Doesn't Create Spellcasting Entry for Custom Staff

### ISSUE THREAD

**Issue by patrickdean** [jessev14/pf2e-staves#9]
I'm creating a custom staff (a Makeshift staff for a Staff Nexus Wizard) and when I add the 'magical' and 'staff' traits to the item, the spellcasting entry isn't created.

Looking at the code, it seems like the hook that adds it only does so when the item is added to the inventory. I don't know anything about what foundry hook options are available, but is it possible to trigger this whenever an item is edited as well?

**Comment by jessev14** [comment]
Hm. That should be possible, but it would a fairly complicated implementation.

If you format the stave's text description correctly before adding it to a character, it should create the spellcasting entry and import the spells automatically. Try starting with a pre-made stave for reference, and then edit the text description to include the spells you want to include.

If that's not an appealing workflow for you, I would have to implement the edit item hook. This module was funded by a commission, so we would have to discuss the cost of the feature if this is the approach you want to take. You can reach me on Discord at `enso#0361` if you'd like to discuss further.

**Comment by patrickdean** [comment]
We also managed to work around by transferring the item to another character and back, so it's not super crucial to implement a solution for this if it complicates things. 

Might be worth an entry in the readme, though. 

Thanks!
